; ---------------------------------------------------------------------------
; fpga.inc
; handy info about locations in the FPGA
; 03-04-19 E. Brombaugh
; ---------------------------------------------------------------------------

.define   GPIO_DATA $1000    ;  GPIO data register location
.define   ACIA_CTRL $1002    ;  ACIA control register location
.define   ACIA_DATA $1003    ;  ACIA data register location
.define   ACIA_SRAM_STORE $3100    ;  ACIA data register location

